version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  nodered:
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - ./node-red:/data
    depends_on:
      - mosquitto

  backend:
    build: ./baken
    ports:
      - "3000:3000"
    volumes:
      - ./baken:/app
    depends_on:
      - mosquitto
